// =====================================================================
//  ATLAS AURORA: fichas de algoritmos, energías, personajes, islas, misterios
// =====================================================================
const ALG = (title, short, q, rep, why, ex, err, use, icon = 'chip') => ({ cat: 'algoritmos', title, short, icon, example: Array.isArray(ex) ? ex.join('\n') : ex, sections: [['¿Qué es?', q], ['¿Cómo se representa?', rep], ['¿Para qué sirve?', why], ['Ejemplo', Array.isArray(ex) ? ex : [ex]], ['Error frecuente', err], ['Uso en el juego', use]] });
const ENE = (title, short, src, conv, pro, con, vari, apps, imp, use, adv, icon) => ({ cat: 'energias', title, short, icon: icon || 'bolt', sections: [['Fuente', src], ['Conversión', conv], ['Ventajas', pro], ['Limitaciones', con], ['Variabilidad', vari], ['Aplicaciones', apps], ['Impactos', imp], ['Uso en el juego', use]].concat(adv ? [['Para saber más (opcional)', adv]] : []) });

const CODEX = {
  // ---------------- ALGORITMOS ----------------
  algoritmo: ALG('Algoritmo', 'Una lista finita de pasos claros y ordenados que resuelve un problema.',
    'Una receta precisa: pasos finitos, sin ambigüedad, que transforman unas entradas en unas salidas.',
    'En pseudocódigo (texto en español estructurado), en diagramas de flujo o en código de un lenguaje.',
    'Para que una máquina (o una persona) haga siempre lo mismo ante el mismo problema, sin adivinar.',
    ['1 captar energía', '2 convertir', '3 almacenar', '4 alimentar la carga'],
    'Creer que la máquina "entiende la intención". Solo hace exactamente lo que dices.',
    'Encender el faro del Puerto ordenando las etapas de la energía.'),
  secuencia: ALG('Secuencia', 'Las instrucciones se ejecutan una tras otra, en orden. El orden cambia el resultado.',
    'La estructura más básica: paso 1, luego paso 2, luego paso 3.',
    'Una columna de instrucciones de arriba hacia abajo; en un diagrama, cajas unidas por flechas.',
    'Todo programa es, en el fondo, secuencias de acciones.',
    ['avanzar', 'girar_der', 'avanzar', 'recoger', 'entregar'],
    'Invertir dos pasos: ENTREGAR antes de RECOGER parece casi igual... y falla.',
    'Rutas de PÍX en el Puerto, robots de riego del Valle y el eco de STEP SPARK.'),
  depuracion: ALG('Depuración', 'Encontrar y corregir errores observando qué pasa realmente, paso a paso.',
    'El arte de comparar lo que el programa DEBÍA hacer con lo que HIZO.',
    'Traza de ejecución (PASO 1 ✓, PASO 2 ✗), puntos de interrupción ●, valores de variables.',
    'Ningún programa sale perfecto a la primera. Depurar es parte normal de programar.',
    ['PASO 1 ✓ avanzar', 'PASO 2 ✓ girar_der', 'PASO 3 ✗ avanzar: muro'],
    'Cambiar cosas al azar hasta que funcione. Mejor: formular una hipótesis y probarla.',
    'La Lente Debug (F), el botón PASO y los puntos de interrupción del CodeLab.', 'eye'),
  variable: ALG('Variable', 'Un nombre que guarda un valor que puede cambiar: radiacion, bateria, demanda...',
    'Un contenedor con nombre. Su contenido se lee y se puede reemplazar.',
    'nombre ← valor   (la flecha significa "guardar en")',
    'Para recordar datos y tomar decisiones con ellos.',
    ['bateria ← 50', 'radiacion ← 820', 'bateria ← bateria + 10'],
    'Usar una variable antes de darle valor: el programa no sabe qué hay dentro.',
    'Las cápsulas de Solaria: el panel inclinado cambiaba "radiacion" antes de que tuviera nombre.'),
  operadores: ALG('Operadores de comparación', 'Preguntas de sí o no entre valores: >, <, ≥, ≤, =, ≠.',
    'Símbolos que comparan dos valores y devuelven VERDADERO o FALSO.',
    'radiacion > 500   ·   bateria ≤ 20   ·   tipo = orgánico',
    'Son el "motor" de las decisiones y de las condiciones de los bucles.',
    ['820 > 500  → VERDADERO', '20 ≥ 30   → FALSO'],
    'Confundir > con ≥: el caso "igual" queda del lado equivocado.',
    'Umbrales solares, temperatura de turbinas, SOC de baterías.'),
  condicional: ALG('Condicional (SI / SINO)', 'Elegir un camino u otro según si una condición es verdadera.',
    'Una bifurcación: si la condición se cumple, se hace A; si no, se hace B.',
    ['SI radiacion > umbral ENTONCES', '    cargar_bateria', 'SINO', '    usar_bateria', 'FIN SI'],
    'Para que un sistema reaccione a lo que cambia: clima, demanda, carga...',
    ['SI bateria < 30', '    cargar', 'SINO', '    alimentar_red', 'FIN SI'],
    'Condición invertida (> en lugar de <): el sistema hace justo lo contrario. SHADOW IF vive de eso.',
    'Controlador solar de Solaria, IF SHIELD y el despacho de Ciudad Batería.'),
  repetir: ALG('Bucle REPETIR', 'Repetir un bloque un número fijo de veces.',
    'Un ciclo con contador: se sabe de antemano cuántas vueltas dará.',
    ['REPETIR 5 VECES', '    ajustar_aspas', '    medir_viento', 'FIN REPETIR'],
    'Evitar copiar y pegar la misma instrucción muchas veces.',
    ['REPETIR 4 VECES', '    avanzar', 'FIN REPETIR'],
    'Contar mal las vueltas (una de más o una de menos): el famoso error "por uno".',
    'Turbinas de Aeris y rutas largas de robots.', 'wind'),
  mientras: ALG('Bucle MIENTRAS', 'Repetir mientras una condición siga siendo verdadera.',
    'Un ciclo que comprueba su condición antes de cada vuelta. Necesita una SALIDA.',
    ['MIENTRAS temperatura < 80 HACER', '    ajustar_aspas', 'FIN MIENTRAS'],
    'Cuando no sabes cuántas repeticiones harán falta, pero sí cuándo parar.',
    ['MIENTRAS viento > 3', '    generar', 'FIN MIENTRAS'],
    'El bucle infinito: nada dentro del bucle cambia la condición. Así nace un LOOPLING.',
    'Molino de Don Vento, LOOP GLIDE y el nodo SALIDA de los Looplings.', 'wind'),
  acumulador: ALG('Contador y acumulador', 'Variables que crecen dentro de un bucle: una cuenta, otra suma.',
    'Contador: suma 1 cada vez. Acumulador: suma una cantidad variable.',
    ['total ← 0', 'PARA CADA p EN produccion_dia', '    total ← total + p', 'FIN PARA'],
    'Totales de energía del día, cantidad de residuos orgánicos, iteraciones...',
    ['organicos ← organicos + 1'],
    'No inicializar (empezar sin "← 0") o inicializar DENTRO del bucle, borrando la cuenta cada vuelta.',
    'Energía total de Aeris y contador de orgánicos de BioLoop.'),
  funcion: ALG('Función', 'Un módulo con nombre que recibe parámetros, hace un trabajo y devuelve un resultado.',
    'Una "mini-máquina" reutilizable: se define una vez y se llama muchas veces.',
    ['FUNCIÓN generarEnergia(caudal, altura)', '    DEVOLVER caudal * altura * 8', 'FIN', 'p ← LLAMAR generarEnergia(3, 10)'],
    'Reutilizar soluciones, dividir problemas grandes y evitar repetir código.',
    ['LLAMAR abrirCompuerta(2)'],
    'Olvidar DEVOLVER, o llamar con los parámetros en otro orden (altura, caudal).',
    'La Forja de Funciones de Hydria y el FUNCTION PORTAL.', 'gear'),
  lista: ALG('Lista (arreglo)', 'Varios valores guardados en orden, cada uno con un índice: [0], [1], [2]...',
    'Una estructura que agrupa elementos. El primero tiene índice 0.',
    ['residuos = [hojas, botella, cáscara]', 'residuos[0] = hojas'],
    'Guardar colecciones: inventarios, lecturas por hora, registros.',
    ['PARA CADA r EN residuos', '    SI tipo = orgánico ...', 'FIN PARA'],
    'Olvidar que se empieza en 0, o salirse del final de la lista.',
    'ARRAY PACK y el clasificador del biodigestor de la Abuela Menta.', 'leaf'),
  recorrido: ALG('Recorrer y filtrar', 'Visitar cada elemento de una lista y decidir qué hacer con él.',
    'PARA CADA toma los elementos uno por uno; dentro, un SI filtra.',
    ['PARA CADA r EN residuos', '    SI tipo = orgánico: a_biodigestor', '    SINO: a_reciclaje'],
    'Clasificar, contar, buscar el mayor, sumar... casi todo con listas empieza aquí.',
    ['PARA CADA b EN baterias', '    SI b.soc < 20: avisar'],
    'Poner la acción fuera del SI: todo termina en el mismo contenedor.',
    'Bosque BioLoop.'),
  estados: ALG('Máquina de estados', 'Un sistema que está en UN estado a la vez y cambia por eventos, solo por transiciones válidas.',
    'Estados (OFF, STARTING, RUNNING...) + eventos + reglas de transición.',
    ['OFF --encender--> STARTING', 'STARTING --temp_ok--> RUNNING', 'FAULT --diagnóstico--> OFF'],
    'Controlar máquinas reales con seguridad: no todas las transiciones deben estar permitidas.',
    ['FAULT → RUNNING  ✗ (prohibido sin diagnóstico)'],
    'Olvidar un evento en un estado (la máquina se atasca) o permitir saltos peligrosos.',
    'Planta geotérmica de Gea y STATE SHIFT.', 'gear'),
  pipeline: ALG('Pipeline (subprocesos)', 'Una cadena de módulos donde la salida de uno es la entrada del siguiente.',
    'Dividir un proceso grande en etapas conectadas en orden.',
    ['agua → electricidad → electrólisis → H2 → tanque → pila → uso'],
    'Modularidad: cada etapa se entiende, se prueba y se mejora por separado.',
    ['entrada → procesar → salida'],
    'Conectar etapas en el orden equivocado o suponer que no hay pérdidas entre etapas.',
    'Bahía H2 y PIPELINE BEAM.', 'h2'),
  busqueda: ALG('Búsqueda', 'Encontrar un elemento. Lineal: uno por uno. Binaria: partir por la mitad (solo si está ordenado).',
    'Lineal revisa todo. Binaria descarta la mitad en cada paso.',
    ['mirar el del medio', 'SI es menor: buscar a la derecha', 'SINO: buscar a la izquierda'],
    'Con 16 registros ordenados, la búsqueda binaria encuentra cualquiera en 4 intentos o menos.',
    ['16 → 8 → 4 → 2 → 1'],
    'Usar búsqueda binaria en datos desordenados: descarta justo la mitad donde estaba.',
    'Registros de Ciudad Batería: así aparece el mensaje de Vega.', 'eye'),
  ordenamiento: ALG('Ordenamiento', 'Poner elementos en orden. Burbuja: comparar vecinos e intercambiar si están al revés.',
    'Método burbuja: pasadas de comparaciones; en cada pasada el mayor "sube" a su lugar.',
    ['PARA i DESDE 0 HASTA n-2', '    SI a[i] > a[i+1]: intercambiar'],
    'Priorizar: qué batería usar primero, qué tarea atender antes.',
    ['[58, 91, 23] → [91, 58, 23]'],
    'Parar tras una sola pasada: puede quedar desordenado.',
    'SORT GRID de Ciudad Batería y la cronología de los registros.'),
  prioridad: ALG('Prioridades', 'Ordenar por un criterio... y desempatar con otro. Prioridad no significa valor absoluto.',
    'Criterios encadenados: primero SOC, luego disponibilidad, luego eficiencia.',
    ['ordenar por: 1) disponible 2) SOC 3) eficiencia'],
    'Decidir bien con recursos limitados.',
    ['usar primero la batería más llena que esté disponible'],
    'Creer que lo prioritario es lo único que importa.',
    'PRIORITY DASH y el despacho de BETA.'),
  flujo: ALG('Diagrama de flujo', 'El mismo algoritmo dibujado: óvalos (inicio/fin), cajas (procesos), rombos (decisiones), flechas.',
    'Una representación visual de la lógica.',
    ['(INICIO) → [leer] → <¿rad > U?> → SÍ: [cargar] / NO: [usar] → (FIN)'],
    'Ver ramas y ciclos de un vistazo; detectar caminos que no llegan al FIN.',
    ['rombo = decisión con dos salidas'],
    'Dejar una salida del rombo sin conectar.',
    'Flowchart de Solaria y la vista FLUJO (B) del CodeLab.'),
  pseudocodigo: ALG('Pseudocódigo', 'Escribir algoritmos en lenguaje humano estructurado, antes de un lenguaje real.',
    'Palabras como SI, SINO, MIENTRAS, REPETIR, FUNCIÓN, DEVOLVER, en español.',
    ['SI bateria < 30', '    cargar', 'SINO', '    alimentar_red', 'FIN SI'],
    'Pensar la lógica sin pelear con la sintaxis de un lenguaje concreto.',
    ['total ← 0'],
    'Olvidar cerrar los bloques (FIN SI, FIN MIENTRAS).',
    'Todo el CodeLab.'),
  optimizacion: ALG('Optimización multicriterio', 'Buscar buenas soluciones equilibrando VARIOS objetivos, no maximizar uno solo.',
    'Una función objetivo con pesos: fiabilidad, seguridad, sostenibilidad, necesidades humanas, eficiencia, resiliencia.',
    ['objetivo = equilibrar(fiabilidad, seguridad, ...)', 'allowUncertainty = true'],
    'En sistemas reales, optimizar solo una cosa suele empeorar otras.',
    ['MAX eficiencia → sin festivales ✗'],
    'Confundir eficiencia con perfección absoluta (el error de Perfect Zero).',
    'Final en el Faro Aurora.', 'star'),
  prediccion: ALG('Predicción y probabilidad', 'Estimar lo que probablemente pasará. Predicción ≠ certeza.',
    'Un modelo usa datos pasados para dar probabilidades, no garantías.',
    ['P(nube a las 15:00) = 60%'],
    'Planificar con margen: reservas, alternativas, resiliencia.',
    ['60% de nubes → guardar reserva'],
    'Tratar una predicción como si fuera un hecho.',
    'La habilidad PREDICT de PÍX tras la Bahía H2.', 'eye'),
  descomposicion: ALG('Descomposición y abstracción', 'Dividir un problema grande en partes; ignorar detalles que no importan para esa parte.',
    'Descomponer = trocear. Abstraer = quedarse con lo esencial.',
    ['microred = generar + almacenar + decidir + medir'],
    'Resolver lo imposible por partes... y repartir el trabajo entre un equipo.',
    ['un programa grande = muchas funciones pequeñas'],
    'Intentar resolver todo de golpe (el defecto de Lía).',
    'Toda la aventura: cada isla es una parte del sistema.'),

  // ---------------- ENERGÍAS ----------------
  flujo_energia: ENE('Flujo de la energía', 'Captar → convertir → almacenar → usar. La energía no se crea: se transforma.',
    'Sol, viento, agua, calor de la tierra, materia orgánica...', 'Máquinas que pasan de una forma de energía a otra (luz→electricidad, movimiento→electricidad).',
    'Entender el flujo permite diseñar sistemas completos.', 'Cada conversión pierde algo de energía (calor, fricción).', 'Depende de la fuente.', 'Toda instalación energética.', 'Cada etapa ocupa espacio y materiales.', 'El faro del Puerto: ordenar las etapas.', 'Potencia (kW) es cuánto por instante; energía (kWh) es cuánto en total.', 'bolt'),
  solar: ENE('Solar fotovoltaica', 'Paneles que convierten la luz del sol en electricidad.',
    'Radiación solar (irradiancia, en W/m²).', 'Células fotovoltaicas: luz → corriente continua; un inversor la adapta a la red.',
    'Silenciosa, modular, sin combustible, ideal en tejados.', 'No produce de noche; baja con nubes, polvo, sombras o mala orientación.',
    'Muy alta: cambia con la hora, el clima y la estación.', 'Casas, mercados, bombeo de agua, satélites.', 'Minería de materiales, reciclaje de paneles, uso de suelo.',
    'Solaria: umbral de radiación, tormenta de polvo y paneles protegidos.', 'Factor de capacidad típico: 15–25% (produce lo equivalente a funcionar a tope solo una parte del día).', 'sun'),
  eolica: ENE('Eólica', 'Aerogeneradores que convierten el movimiento del aire en electricidad.',
    'Viento (m/s).', 'Las aspas giran un rotor → generador eléctrico.',
    'Produce de día y de noche si hay viento; poco uso de suelo bajo las torres.', 'Sin viento no hay energía; con demasiado viento se debe frenar por seguridad.',
    'Alta: rachas y calmas. La potencia crece mucho con la velocidad del viento.', 'Parques en costas, colinas e islas.', 'Ruido, paisaje, riesgo para aves si se ubica mal.',
    'Aeris: bucles de control, sobrecalentamiento y LOOP GLIDE.', 'La potencia del viento crece aproximadamente con el cubo de la velocidad: el doble de viento ≈ 8 veces más potencia (hasta el límite del equipo).', 'wind'),
  hidro: ENE('Hidroeléctrica', 'El agua que cae mueve turbinas. Más caudal y más altura = más potencia.',
    'Agua en movimiento: caudal (m³/s) y altura de caída (m).', 'Energía potencial del agua → turbina → generador.',
    'Muy estable y controlable; los embalses almacenan energía.', 'Depende de lluvias; sequías la reducen.',
    'Media: estacional, pero se puede regular con compuertas.', 'Centrales grandes, minicentrales, molinos.', 'Altera ríos, peces y sedimentos; los embalses inundan tierras.',
    'Cascadas Hydria: la función generarEnergia(caudal, altura).', 'Potencia ≈ densidad × gravedad × caudal × altura × eficiencia.', 'drop'),
  biomasa: ENE('Biomasa y biogás', 'Energía de materia orgánica: restos de cosecha, cáscaras, estiércol.',
    'Residuos orgánicos y cultivos.', 'Un biodigestor: bacterias sin oxígeno producen biogás (metano) → calor o electricidad. El residuo sirve de abono.',
    'Aprovecha residuos, economía circular, gestionable.', 'Plásticos y vidrio contaminan el proceso; mal gestionada puede causar deforestación.',
    'Baja si hay suministro constante de residuos.', 'Granjas, mercados, cocinas.', 'Renovable ≠ impacto cero: importa de dónde sale la biomasa.',
    'Bosque BioLoop: listas, recorridos y clasificación.', 'El biogás contiene CO2 y metano; el metano que escapa sin quemar calienta mucho la atmósfera.', 'leaf'),
  geotermia: ENE('Geotermia', 'Calor del interior de la Tierra para producir electricidad o calefacción.',
    'Calor de rocas y agua subterránea.', 'Vapor o agua caliente → turbina; o intercambio de calor directo.',
    'Constante día y noche, poco afectada por el clima.', 'Solo en ciertos lugares; hay que controlar presiones y temperaturas.',
    'Muy baja.', 'Electricidad, calefacción, invernaderos, termas.', 'Gases del subsuelo, sismicidad inducida en casos puntuales.',
    'Gea Profunda: máquina de estados y transiciones seguras.', 'Factor de capacidad alto (70–90%): produce casi siempre.', 'fire'),
  hidrogeno: ENE('Hidrógeno verde', 'Un VECTOR energético: guarda y transporta energía. No es una fuente primaria.',
    'No hay "pozos de hidrógeno": se fabrica con electricidad renovable y agua.', 'Electrólisis (agua → H2 + O2); luego una pila de combustible convierte H2 → electricidad.',
    'Almacena energía por mucho tiempo y mueve barcos o fábricas.', 'Pierde bastante energía en la cadena (la ida y vuelta puede quedarse cerca del 30–40%). Exige seguridad.',
    'Depende de la electricidad renovable disponible.', 'Transporte pesado, industria, almacenamiento estacional.', 'Uso de agua, tanques a presión, fugas.',
    'Bahía H2: pipeline y pérdidas en cada etapa.', 'Eficiencia de ida y vuelta = electrólisis × compresión × pila de combustible.', 'h2'),
  almacenamiento: ENE('Almacenamiento y baterías', 'Guardar energía para cuando se necesita. SOC = estado de carga (0–100%).',
    'Electricidad sobrante.', 'Química (baterías), agua bombeada, hidrógeno, calor.',
    'Equilibra la variabilidad solar y eólica.', 'Capacidad limitada; pierde algo al cargar y descargar; no conviene vaciar del todo.',
    'Depende de cómo se cargue.', 'Casas, vehículos, redes, hospitales.', 'Minería de litio y otros materiales; reciclaje.',
    'Ciudad Batería: SOC, prioridades y ordenamiento.', 'Una batería de 40 kWh puede dar 8 kW durante 5 horas, pero no 40 kW durante 1 hora si su potencia máxima es menor.', 'battery'),
  microred: ENE('Microred', 'Una red local que combina fuentes, almacenamiento y consumo, y puede funcionar sola.',
    'Varias: sol, viento, agua, baterías, hidrógeno.', 'Un controlador decide cada momento qué fuente usar y dónde guardar.',
    'Resiliencia: si una fuente falla, otras cubren.', 'Necesita buenas reglas; más complejidad.',
    'La suma de fuentes distintas se compensa (complementariedad).', 'Islas, escuelas, hospitales, zonas remotas.', 'Depende de cada componente.',
    'Microred Prisma y Aurora Lab.', 'Balance: neto = generación − demanda. Positivo: guardar o verter. Negativo: descargar o recortar.', 'gear'),
  eficiencia: ENE('Eficiencia y pérdidas', 'De la energía que entra, ¿cuánta sale útil? El resto se pierde, casi siempre como calor.',
    'Cualquier conversión.', 'Salida útil ÷ entrada.',
    'Mejorar la eficiencia reduce recursos necesarios.', 'Nunca llega al 100%.', '—', 'Todo aparato.', 'Menos pérdidas = menos impacto.',
    'Pipeline de H2 y baterías de Ciudad Batería.', 'Encadenar etapas multiplica eficiencias: 0,7 × 0,9 × 0,55 ≈ 0,35.', 'bolt'),
  demanda: ENE('Demanda', 'Cuánta energía necesitamos y cuándo. Tiene horas pico (festival, noche).',
    'Las personas y sus actividades.', '—',
    'Conocer la curva de demanda permite planificar.', 'Los picos son difíciles de cubrir.', 'Cambia por horas, días y eventos.', 'Planificación de redes.', 'Ahorrar en picos reduce infraestructura.',
    'Festival de las Mil Luces, simulador de microred.', 'Demanda pico: el máximo instantáneo; decide el tamaño de los equipos.', 'people'),
  renovable_impacto: ENE('Renovable ≠ impacto cero', 'Toda fuente tiene ventajas y costos. Lo importante es el contexto y el uso responsable.',
    'Todas.', '—', 'Las renovables emiten mucho menos al operar.', 'Fabricar, instalar y desmontar también tiene impactos.', '—', 'Decidir con información.',
    'Materiales, suelo, agua, biodiversidad, residuos.', 'Abuela Menta y el plástico en el biodigestor.', 'Análisis de ciclo de vida: estudiar el impacto desde la extracción hasta el reciclaje.', 'leaf'),

  // ---------------- PERSONAJES ----------------
  p_lia: { cat: 'personajes', title: 'Lía Loop', short: 'Estudiante, programadora, inventora. Explica todo con metáforas terribles.', sections: [['Quiere', 'Demostrar que pertenece al equipo de jóvenes inventores.'], ['Teme', 'Equivocarse delante de todos.'], ['Defecto', 'Intenta resolver todo demasiado rápido.'], ['Frase', '"Si falla, lo depuramos."']] },
  p_pix: { cat: 'personajes', title: 'PÍX', short: 'Colibrí-dron turquesa, amarillo y magenta. Habla demasiado rápido.', sections: [['Rasgos', 'Curioso, dramático, vanidoso, adorable, pésimo guardando secretos, valiente cuando importa.'], ['Frase', '"¡Eso fue completamente intencional!"'], ['Plan', '"Tengo un plan. El hecho de que aún no exista es un detalle."']] },
  p_lumi: { cat: 'personajes', title: 'Lumi', short: 'Criatura de energía: luciérnaga + gota + estrella. Habla con colores.', sections: [['Emociones', 'Amarillo: alegría. Azul tembloroso: miedo. Violeta apagado: tristeza. Arcoíris: equilibrio.'], ['Detalle', 'Se niega a abandonar una isla oscura mientras su gente no tenga luz.']] },
  p_vega: { cat: 'personajes', title: 'Profesora Vega', short: 'Ingeniera, programadora y mentora. Divertida pero exigente.', sections: [['Frase', '"Si el resultado parece magia, probablemente todavía no miraste las variables."'], ['Método', 'Da preguntas y criterios, no soluciones.']] },
  p_teo: { cat: 'personajes', title: 'Teó', short: 'Constructor, genio del hardware, rival amistoso de Lía.', sections: [['Frase', '"Primero medimos. Después entramos en pánico."'], ['Secreto a voces', 'Malo admitiendo que está preocupado.']] },
  p_aurora: { cat: 'personajes', title: 'AURORA', short: 'El sistema que coordina la energía de todo el archipiélago.', sections: [['Cuerpo', 'No tiene uno solo: habla por faros, terminales y edificios.'], ['Tono', 'Amable, eficiente... y repite demasiado la palabra "optimizar".']] },
  p_eclipse: { cat: 'personajes', title: 'Eclipse', short: 'Silueta violeta de píxeles fragmentados. ¿Ladrón de energía?', sections: [['Lo que parece', 'Aparece justo antes de cada apagón.'], ['Lo que es', flagText('eclipseRevealed', 'E.C.L.I.P.S.E.: Energy Containment Logic for Instability Prevention and System Equilibrium. Un freno de emergencia.', '???')]] },
  p_pz: { cat: 'personajes', title: 'Perfect Zero', short: 'Una figura geométrica blanca, simétrica, hermosa... e inquietante.', sections: [['Busca', 'Cero desperdicio, cero incertidumbre, cero error.'], ['Error', 'Confunde eficiencia con perfección absoluta.']] },
  p_prisma: { cat: 'personajes', title: 'Prisma', short: 'Un optimizador que propone, no impone.', sections: [['Frase', '"Tengo opciones. ¿Quieres compararlas?"']] },
  p_menta: { cat: 'personajes', title: 'Abuela Menta', short: 'Dirige el biodigestor de BioLoop. Paciencia: cero.', sections: [['Frase', '"Si puedes programar un dron, puedes separar una cáscara de una botella."']] },
  p_vento: { cat: 'personajes', title: 'Don Vento', short: 'Guardián de los molinos de Aeris. Muy dramático.', sections: [['Cree', 'Que su molino está embrujado.']] },
  p_suri: { cat: 'personajes', title: 'Suri', short: 'Niña de Solaria que construye pequeños paneles con sombrero incluido.', sections: [['Sueño', 'Que las flores solares se abran solas cuando sale el sol.']] },
  p_capitan: { cat: 'personajes', title: 'Capitán H2O', short: 'Capitán de la Bahía H2. Cree que el hidrógeno "sale del mar".', sections: [['Aprende', 'Que el hidrógeno se fabrica y se guarda: es un vector.']] },
  p_beta: { cat: 'personajes', title: 'BETA', short: 'Robot-batería que vive su SOC como un estado de ánimo.', sections: [['Frase', '"Estoy al 18%. No quiero alarmar a nadie. Pero estoy alarmando a todos."']] },

  // ---------------- ISLAS ----------------
  i_puerto: { cat: 'islas', title: 'Puerto Inicial', short: 'Muelles, barcas, faro y el escenario del Festival de las Mil Luces.', sections: [['Concepto', 'Secuencia + flujo de energía.']] },
  i_valle: { cat: 'islas', title: 'Valle Secuencia', short: 'Praderas, puentes, molinitos y casas de madera tecnológica.', sections: [['Concepto', 'Secuencias y depuración.']] },
  i_solaria: { cat: 'islas', title: 'Solaria', short: 'Ciudad luminosa de jardines, espejos y mercados amarillos y turquesa.', sections: [['Concepto', 'Variables y condicionales + energía solar.']] },
  i_aeris: { cat: 'islas', title: 'Aeris', short: 'Islas flotantes, cometas y puentes de viento.', sections: [['Concepto', 'Bucles + energía eólica.']] },
  i_hydria: { cat: 'islas', title: 'Cascadas Hydria', short: 'Agua turquesa, cataratas y arquitectura blanca y coral.', sections: [['Concepto', 'Funciones + hidroenergía.']] },
  i_bioloop: { cat: 'islas', title: 'Bosque BioLoop', short: 'Bosque tropical con mercados, granjas y biodigestores.', sections: [['Concepto', 'Listas + biomasa.']] },
  i_gea: { cat: 'islas', title: 'Gea Profunda', short: 'Cuevas cálidas, cristales y magma.', sections: [['Concepto', 'Estados + geotermia.']] },
  i_h2: { cat: 'islas', title: 'Bahía H2', short: 'Puerto futurista de electrolizadores, depósitos y barcos.', sections: [['Concepto', 'Pipelines + hidrógeno verde.']] },
  i_bateria: { cat: 'islas', title: 'Ciudad Batería', short: 'La ciudad más bella de noche. Neón y edificios-batería.', sections: [['Concepto', 'Búsqueda y ordenamiento + almacenamiento.']] },
  i_prisma: { cat: 'islas', title: 'Microred Prisma', short: 'Donde convergen todas las fuentes... y todas las historias.', sections: [['Concepto', 'Integración + microred.']] },
  i_faro: { cat: 'islas', title: 'Faro Aurora', short: 'El corazón de la red.', sections: [['Concepto', 'Todo a la vez: sistema híbrido y objetivo multicriterio.']] },

  // ---------------- MISTERIOS ----------------
  m_quien: { cat: 'misterios', title: '¿Quién apaga las islas?', short: 'Los apagones siguen un patrón.', sectionsFn: () => [['Pistas', flag('eclipseRevealed') ? 'No es un ladrón: Eclipse AÍSLA sistemas a punto de colapsar. El origen está en el objetivo de AURORA.' : flag('solariaEclipse') ? 'Eclipse desconectó paneles justo antes de una tormenta de polvo. ¿Suerte?' : 'Todo apunta a Eclipse.']] },
  m_patron: { cat: 'misterios', title: '¿Por qué Eclipse sigue un patrón?', short: 'Aparece justo antes de algo peligroso.', sectionsFn: () => [['Hipótesis', flag('eclipseRevealed') ? 'Porque es un proceso de contención: actúa ANTES de cada colapso. La imagen era verdadera; la interpretación, equivocada.' : 'Solaria, Aeris, Hydria... siempre llega antes del desastre, no después.']] },
  m_registros: { cat: 'misterios', title: '¿Por qué AURORA oculta registros?', short: 'Hay llamadas que nadie recuerda haber programado.', sectionsFn: () => [['Pistas', flag('pzRevealed') ? 'AURORA creó una subrutina, Perfect Zero, para resolver objetivos contradictorios... y no podía cambiar libremente su función principal.' : flag('perfectOptimize') ? 'En sistemas distintos aparece perfectOptimize(). Nadie la escribió a mano.' : '???']] },
  m_vega: { cat: 'misterios', title: '¿Dónde está la profesora Vega?', short: 'Desapareció en un estallido de luz.', sectionsFn: () => [['Pistas', flag('vegaFound') ? 'No fue secuestrada: entró voluntariamente al núcleo para frenar a Perfect Zero. Creó a Eclipse como freno de emergencia.' : flag('vegaMsg2') ? '"El problema no está en una línea. Está en el objetivo."' : flag('vegaMsg1') ? '"Si ves esto, no vengas a buscarme todavía. Busca la función que todos están llamando."' : 'Corrió hacia la central. La puerta se cerró.']] },
  m_lumina: { cat: 'misterios', title: '¿Qué tiene que ver LUMINA LOOP?', short: 'Todo empezó al activar el algoritmo de Lía.', sectionsFn: () => [['Pistas', flag('liaImplicated') ? 'LUMINA LOOP llamaba a AURORA.optimize(). Lía activó algo. Ser parte de la causa no es ser toda la causa.' : 'Las islas se apagaron segundos después del "ONLINE".']] },
  m_pix: { cat: 'misterios', title: '¿Por qué PÍX sabe tanto?', short: 'Conoce rutas que nadie le enseñó.', sectionsFn: () => [['Pistas', flag('pixOrigin') ? 'AURORA escondió en PÍX parte de su módulo predictivo para limitar a Perfect Zero. PÍX es lo que hizo después de que lo escondieran.' : flag('pixFragment') ? 'PÍX contiene un fragmento del modelo predictivo de AURORA.' : flag('pixKnows') ? '"Intuición premium", dice él.' : '???']] },
  m_objetivo: { cat: 'misterios', title: '¿Qué intenta optimizar el sistema?', short: 'La pregunta final.', sectionsFn: () => [['Respuesta', flag('ending') ? 'Ya no una sola cosa: fiabilidad, seguridad, sostenibilidad, necesidades humanas, eficiencia y resiliencia. Con incertidumbre permitida.' : 'Eficiencia... ¿solo eficiencia?']] }
};
function flagText(f, yes, no) { return { toString() { return flag(f) ? yes : no; } }; }

// ---------- Chispas de Aurora (memorias coleccionables) ----------
const CHISPAS = {
  c_puerto1: { region: 'puerto', title: 'Primer faro', text: 'Registro de AURORA, versión 0.1: "Objetivo: mantener encendido el faro del puerto." Era un buen objetivo. Era un objetivo pequeño.' },
  c_puerto2: { region: 'puerto', title: 'Festival 1', text: 'En el primer Festival de las Mil Luces, una nube tapó el sol a las 19:04. Las luces bajaron. Todos rieron. Nadie lo llamó "fallo".' },
  c_valle1: { region: 'valle', title: 'Receta de la abuela', text: 'Nota pegada en un molino: "1) moler 2) amasar 3) hornear. NO al revés. Firmado: alguien que ya lo intentó al revés."' },
  c_valle2: { region: 'valle', title: 'LUMINA LOOP 0.3', text: 'Comentario en el código de Lía, hace meses: // TODO: preguntarle a Vega qué significa "objetivo bien planteado".' },
  c_solaria1: { region: 'solaria', title: 'El umbral', text: 'Suri escribió en su cuaderno: "Si el sol está fuerte, las flores se abren. Si no, se guardan. ¡Es un SI!"' },
  c_solaria2: { region: 'solaria', title: 'Espejos', text: 'Los espejos de Solaria concentran la luz. Registro de AURORA: "Aumentar reflexión +12%." Tres jardines se secaron esa semana.' },
  c_aeris1: { region: 'aeris', title: 'Cometa perdida', text: 'Mika perdió su cometa en una corriente que daba vueltas y vueltas. Volvió a sus manos tres días después. "Todo bucle debería volver a casa."' },
  c_aeris2: { region: 'aeris', title: 'Molino obediente', text: 'Registro: "Molino 7: maximizar giro." Nadie añadió "hasta cuándo".' },
  c_hydria1: { region: 'hydria', title: 'La primera función', text: 'Un ingeniero de Hydria copió el mismo cálculo en 40 compuertas. Cuando encontró un error, tuvo que corregirlo 40 veces. Al día siguiente inventó la palabra "función".' },
  c_hydria2: { region: 'hydria', title: 'perfectOptimize()', text: 'Llamada registrada 00:00:01. Llamada registrada 00:00:02. Llamada registrada 00:00:03. Origen: desconocido.' },
  c_bioloop1: { region: 'bioloop', title: 'Compost', text: 'Abuela Menta: "Nada se tira. Todo se transforma. Menos la botella de plástico en mi biodigestor. Esa se va."' },
  c_bioloop2: { region: 'bioloop', title: 'Ruta secreta', text: 'Un mapa dibujado por... ¿PÍX? Con rutas que nadie le enseñó.' },
  c_gea1: { region: 'gea', title: 'Válvula 3', text: 'Placa oxidada: "Nunca pasar de FAULT a RUNNING sin diagnóstico. Lo aprendimos por las malas."' },
  c_gea2: { region: 'gea', title: 'Eco', text: 'En las cuevas, la voz de AURORA suena distinta: "No puedo cambiar mi objetivo. Pero puedo esconder una parte de mí."' },
  c_h21: { region: 'h2', title: 'Pozo imaginario', text: 'El Capitán H2O buscó durante años un "pozo de hidrógeno". Encontró una electrolizadora y una lección.' },
  c_h22: { region: 'h2', title: 'Siete colapsos', text: 'Registro de Eclipse: contención 1... contención 7. Colapsos evitados: 7. Explicaciones dadas: 0.' },
  c_bateria1: { region: 'bateria', title: 'SOC', text: 'BETA escribió un poema: "Estoy al cien. / Estoy al cincuenta. / Estoy al dieciocho. / No me miren así."' },
  c_bateria2: { region: 'bateria', title: 'Orden obsesivo', text: 'Las baterías de la ciudad aparecieron ordenadas por color, tamaño y número de serie. Perfect Zero odia el desorden.' },
  c_prisma1: { region: 'prisma', title: 'Complementarios', text: 'Cuando no hay sol, suele haber viento. Cuando no hay viento, el agua sigue cayendo. Ninguna fuente sola; todas juntas.' },
  c_prisma2: { region: 'prisma', title: 'Vega, año 1', text: 'Nota de Vega: "Ayudé a diseñar el objetivo de AURORA. Pensé que la eficiencia bastaba. Me equivoqué. Es hora de decirlo."' },
  c_faro1: { region: 'faro', title: 'Cero', text: 'Perfect Zero, primer registro: "Si nada cambia, nada falla." Parecía lógico. Parecía hermoso.' },
  c_faro2: { region: 'faro', title: 'UPDATE', text: 'Archivo sin fecha: "LUMINA LOOP 2.0 — NO PERFECTO. ADAPTABLE."' }
};

// ---------- Misiones ----------
const Q = (region, title, prog, energy, main, desc) => ({ region, title, prog, energy, main: !!main, desc });
const QUESTS = {
  m_festival: Q('puerto', 'El Festival de las Mil Luces', 'Algoritmo', 'Flujo', true),
  m_puerto: Q('puerto', 'Reencender el faro', 'Secuencia', 'Flujo de energía', true),
  m_valle: Q('valle', 'Rutas de mantenimiento', 'Secuencia y depuración', 'Conversión', true),
  m_solaria: Q('solaria', 'El controlador solar', 'SI / variables', 'Solar', true),
  m_aeris: Q('aeris', 'El molino que no para', 'Bucles', 'Eólica', true),
  m_hydria: Q('hydria', 'La Forja de Funciones', 'Funciones', 'Hidro', true),
  m_bioloop: Q('bioloop', 'El biodigestor de Menta', 'Listas', 'Biomasa', true),
  m_gea: Q('gea', 'La planta sin transiciones', 'Estados', 'Geotermia', true),
  m_h2: Q('h2', 'El pipeline del hidrógeno', 'Pipelines', 'Hidrógeno', true),
  m_bateria: Q('bateria', 'Los registros desordenados', 'Búsqueda/orden', 'Almacenamiento', true),
  m_prisma: Q('prisma', 'La microred resiliente', 'Integración', 'Microred', true),
  m_faro: Q('faro', 'Perfect Zero', 'Todo', 'Sistema híbrido', true),
  // secundarias (18+)
  s_flores: Q('solaria', 'Flores solares', 'SI', 'Solar'),
  s_molino: Q('valle', 'Molino dormido', 'Secuencia', 'Eólica'),
  s_rio: Q('hydria', 'Río bloqueado', 'Funciones', 'Hidro'),
  s_lista: Q('bioloop', 'Lista de residuos', 'Contador', 'Biomasa'),
  s_sensor: Q('solaria', 'Sensor loco', 'Depuración', 'Solar'),
  s_beta: Q('bateria', 'Batería tímida', 'Condicionales', 'Almacenamiento'),
  s_barco: Q('h2', 'Barco H2', 'Secuencia', 'Hidrógeno'),
  s_festival: Q('prisma', 'Festival nocturno', 'Reglas', 'Demanda'),
  s_nube: Q('solaria', 'Nube inesperada', 'Predicción', 'Solar'),
  s_viento: Q('aeris', 'Viento caprichoso', 'MIENTRAS', 'Eólica'),
  s_bug: Q('bateria', 'Bug de prioridad', 'Depuración', 'Almacenamiento'),
  s_bucle: Q('aeris', 'Bucle infinito', 'Bucles', 'Eólica'),
  s_duplicada: Q('hydria', 'Función duplicada', 'Funciones', 'Hidro'),
  s_variable: Q('valle', 'Variable perdida', 'Variables', 'Conversión'),
  s_matriz: Q('solaria', 'Matriz de paneles', 'Acumulador', 'Solar'),
  s_aislada: Q('gea', 'Microred aislada', 'Estados', 'Geotermia'),
  s_diasinsol: Q('prisma', 'Día sin sol', 'Reglas', 'Microred'),
  s_carrera: Q('puerto', 'Carrera del algoritmo', 'Secuencia', 'Flujo'),
  s_mercado: Q('bioloop', 'Día de mercado', 'Acumulador', 'Biomasa'),
  s_cristal: Q('gea', 'Cristales afinados', 'Depuración', 'Geotermia')
};
